// Code generated by MockGen. DO NOT EDIT.
// Source: analytics.go
//
// Generated by this command:
//
//	mockgen -source=analytics.go -package=analytics -destination=./mock/analytics.go
//

// Package analytics is a generated GoMock package.
package analytics

import (
	context "context"
	reflect "reflect"

	analytics "github.com/hitesh22rana/chronoverse/internal/model/analytics"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserAnalytics mocks base method.
func (m *MockRepository) GetUserAnalytics(ctx context.Context, userID string) (*analytics.GetUserAnalyticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAnalytics", ctx, userID)
	ret0, _ := ret[0].(*analytics.GetUserAnalyticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAnalytics indicates an expected call of GetUserAnalytics.
func (mr *MockRepositoryMockRecorder) GetUserAnalytics(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAnalytics", reflect.TypeOf((*MockRepository)(nil).GetUserAnalytics), ctx, userID)
}

// GetWorkflowAnalytics mocks base method.
func (m *MockRepository) GetWorkflowAnalytics(ctx context.Context, userID, workflowID string) (*analytics.GetWorkflowAnalyticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowAnalytics", ctx, userID, workflowID)
	ret0, _ := ret[0].(*analytics.GetWorkflowAnalyticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowAnalytics indicates an expected call of GetWorkflowAnalytics.
func (mr *MockRepositoryMockRecorder) GetWorkflowAnalytics(ctx, userID, workflowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowAnalytics", reflect.TypeOf((*MockRepository)(nil).GetWorkflowAnalytics), ctx, userID, workflowID)
}
