apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: chronoverse
  labels:
    app: clickhouse
    component: database
data:
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-connection-config
  namespace: chronoverse
  labels:
    app: clickhouse
    component: database
data:
  CLICKHOUSE_HOSTS: "clickhouse:9000"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: chronoverse
  labels:
    app: clickhouse
    component: database
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
        component: database
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 9000
          name: clickhouse
        envFrom:
        - configMapRef:
            name: clickhouse-config
        resources:
          limits:
            cpu: "2000m"
            memory: "3072Mi"
          requests:
            cpu: "500m"
            memory: "1024Mi"
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
        livenessProbe:
          exec:
            command:
            - clickhouse-client
            - --host=localhost
            - --query=SELECT 1
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - clickhouse-client
            - --host=localhost
            - --query=SELECT 1
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: clickhouse-storage
        persistentVolumeClaim:
          claimName: clickhouse-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: chronoverse
  labels:
    app: clickhouse
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: clickhouse
    component: database
  ports:
  - port: 9000
    targetPort: 9000
    name: clickhouse
