apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: chronoverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      initContainers:
      - name: wait-for-certs
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          while [ ! -f /certs/auth.ed ] || [ ! -f /certs/auth.ed.pub ]; do 
            echo "Waiting for certificates..."
            sleep 1
          done
          echo "✅ Certificates found!"
        volumeMounts:
        - name: certs-storage
          mountPath: /certs
      containers:
      - name: notifications-service
        image: ghcr.io/hitesh22rana/chronoverse/notifications-service:latest
        ports:
        - containerPort: 50054
        envFrom:
        - configMapRef:
            name: database-config
        - secretRef:
            name: database-secrets
        - configMapRef:
            name: grpc-config
        - configMapRef:
            name: notifications-service-config
        - configMapRef:
            name: observability-config
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: certs-storage
          mountPath: /certs
        livenessProbe:
          exec:
            command:
            - /bin/grpc-health-probe
            - -addr=localhost:50054
            - -connect-timeout=250ms
            - -rpc-timeout=250ms
            - -tls
            - -tls-ca-cert=certs/ca/ca.crt
            - -tls-client-cert=certs/notifications-service/notifications-service.crt
            - -tls-client-key=certs/notifications-service/notifications-service.key
            - -tls-server-name=notifications-service
            - -rpc-header=Audience:grpc_probe
            - -rpc-header=Role:admin
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/grpc-health-probe
            - -addr=localhost:50054
            - -connect-timeout=250ms
            - -rpc-timeout=250ms
            - -tls
            - -tls-ca-cert=certs/ca/ca.crt
            - -tls-client-cert=certs/notifications-service/notifications-service.crt
            - -tls-client-key=certs/notifications-service/notifications-service.key
            - -tls-server-name=notifications-service
            - -rpc-header=Audience:grpc_probe
            - -rpc-header=Role:admin
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: certs-storage
        hostPath:
          path: /tmp/chronoverse-certs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: chronoverse
spec:
  selector:
    app: notifications-service
  ports:
  - port: 50054
    targetPort: 50054