CREATE TYPE JOB_TRIGGER AS ENUM ('AUTOMATIC', 'MANUAL');

ALTER TABLE jobs ADD COLUMN "trigger" JOB_TRIGGER NOT NULL DEFAULT 'AUTOMATIC';

CREATE INDEX IF NOT EXISTS idx_jobs_trigger ON jobs ("trigger");