DROP TYPE IF EXISTS STATUS;

CREATE TYPE STATUS AS ENUM ('UNVERIFIED', 'VERIFIED', 'DEACTIVATED');
CREATE TYPE NOTIFICATION_TYPE AS ENUM ('EMAIL', 'SMS', 'PUSH');
CREATE TYPE NOTIFICATION_PREFERENCE AS ENUM ('ALERTS', 'ALL', 'NONE');

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    status STATUS DEFAULT 'UNVERIFIED' NOT NULL,
    notification_preference NOTIFICATION_PREFERENCE DEFAULT 'ALERTS' NOT NULL,
    notification_type NOTIFICATION_TYPE DEFAULT 'EMAIL' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc') NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);