DROP TRIGGER IF EXISTS trigger_update_users ON users;

DROP FUNCTION IF EXISTS update_users_updated_at;

DROP INDEX IF EXISTS idx_users_email;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS USER_STATUS;
DROP TYPE IF EXISTS NOTIFICATION_CHANNEL;
DROP TYPE IF EXISTS NOTIFICATION_PREFERENCE;