DROP TYPE IF EXISTS USER_STATUS;
DROP TYPE IF EXISTS NOTIFICATION_CHANNEL;
DROP TYPE IF EXISTS NOTIFICATION_PREFERENCE;

CREATE TYPE USER_STATUS AS ENUM ('UNVERIFIED', 'VERIFIED', 'DEACTIVATED');
CREATE TYPE NOTIFICATION_CHANNEL AS ENUM ('EMAIL', 'SMS', 'PUSH');  -- Delivery channel
CREATE TYPE NOTIFICATION_PREFERENCE AS ENUM ('ALERTS', 'ALL', 'NONE');  -- Notification frequency/preference

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    status USER_STATUS DEFAULT 'UNVERIFIED' NOT NULL,
    notification_channel NOTIFICATION_CHANNEL[] DEFAULT ARRAY['EMAIL']::NOTIFICATION_CHANNEL[],
    notification_preference NOTIFICATION_PREFERENCE DEFAULT 'ALERTS' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc') NOT NULL
);

-- Auto-update updated_at on row updates
CREATE OR REPLACE FUNCTION update_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now() AT TIME ZONE 'utc';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_users_updated_at();