apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronoverse-sa
  namespace: chronoverse
  labels:
    app: chronoverse
    component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chronoverse
  name: chronoverse-role
  labels:
    app: chronoverse
    component: role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chronoverse-rolebinding
  namespace: chronoverse
  labels:
    app: chronoverse
    component: rolebinding
subjects:
- kind: ServiceAccount
  name: chronoverse-sa
  namespace: chronoverse
roleRef:
  kind: Role
  name: chronoverse-role
  apiGroup: rbac.authorization.k8s.io
