apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chronoverse

labels:
- pairs:
    app.kubernetes.io/part-of: chronoverse

resources:
- namespace.yaml
- configmaps.yaml
- rbac.yaml
- network-policy.yaml
- docker-proxy.yaml
- services.yaml
- workloads.yaml
- init-kafka-topics.yaml
- nginx.yaml
- ingress.yaml
- pod-disruption-budgets.yaml

