apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chronoverse

labels:
- pairs:
    app.kubernetes.io/part-of: chronoverse

resources:
- namespace.yaml
- configmaps.yaml
- rbac.yaml
- network-policy.yaml
- docker-proxy.yaml
- services.yaml
- workloads.yaml
- init-kafka-topics.yaml
- nginx.yaml
- ingress.yaml
- pod-disruption-budgets.yaml

patches:
- target:
    kind: Deployment
    labelSelector: chronoverse.io/certs=true
  patch: |-
    - op: replace
      path: /spec/template/spec/securityContext
      value:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
- target:
    kind: Job
    name: database-migration
  patch: |-
    - op: replace
      path: /spec/template/spec/securityContext
      value:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
- target:
    kind: Job
    name: init-kafka-topics
  patch: |-
    - op: replace
      path: /spec/template/spec/securityContext
      value:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
