apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: users-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: users-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workflows-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflows-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jobs-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jobs-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notifications-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notifications-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: analytics-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workflow-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: execution-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: execution-worker
