// Code generated by MockGen. DO NOT EDIT.
// Source: jobs.go
//
// Generated by this command:
//
//	mockgen -source=jobs.go -package=jobs -destination=./mock/jobs.go
//

// Package jobs is a generated GoMock package.
package jobs

import (
	context "context"
	reflect "reflect"

	model "github.com/hitesh22rana/chronoverse/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockRepository) CreateJob(ctx context.Context, userID, name, payload, kind string, interval int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, userID, name, payload, kind, interval)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockRepositoryMockRecorder) CreateJob(ctx, userID, name, payload, kind, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockRepository)(nil).CreateJob), ctx, userID, name, payload, kind, interval)
}

// GetJob mocks base method.
func (m *MockRepository) GetJob(ctx context.Context, jobID, userID string) (*model.GetJobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID, userID)
	ret0, _ := ret[0].(*model.GetJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockRepositoryMockRecorder) GetJob(ctx, jobID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockRepository)(nil).GetJob), ctx, jobID, userID)
}

// GetJobByID mocks base method.
func (m *MockRepository) GetJobByID(ctx context.Context, jobID string) (*model.GetJobByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByID", ctx, jobID)
	ret0, _ := ret[0].(*model.GetJobByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByID indicates an expected call of GetJobByID.
func (mr *MockRepositoryMockRecorder) GetJobByID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByID", reflect.TypeOf((*MockRepository)(nil).GetJobByID), ctx, jobID)
}

// GetScheduledJobByID mocks base method.
func (m *MockRepository) GetScheduledJobByID(ctx context.Context, scheduledJobID string) (*model.GetScheduledJobByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledJobByID", ctx, scheduledJobID)
	ret0, _ := ret[0].(*model.GetScheduledJobByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledJobByID indicates an expected call of GetScheduledJobByID.
func (mr *MockRepositoryMockRecorder) GetScheduledJobByID(ctx, scheduledJobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledJobByID", reflect.TypeOf((*MockRepository)(nil).GetScheduledJobByID), ctx, scheduledJobID)
}

// ListJobsByUserID mocks base method.
func (m *MockRepository) ListJobsByUserID(ctx context.Context, userID, cursor string) (*model.ListJobsByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobsByUserID", ctx, userID, cursor)
	ret0, _ := ret[0].(*model.ListJobsByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobsByUserID indicates an expected call of ListJobsByUserID.
func (mr *MockRepositoryMockRecorder) ListJobsByUserID(ctx, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobsByUserID", reflect.TypeOf((*MockRepository)(nil).ListJobsByUserID), ctx, userID, cursor)
}

// ListScheduledJobs mocks base method.
func (m *MockRepository) ListScheduledJobs(ctx context.Context, scheduledJobID, userID, cursor string) (*model.ListScheduledJobsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduledJobs", ctx, scheduledJobID, userID, cursor)
	ret0, _ := ret[0].(*model.ListScheduledJobsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduledJobs indicates an expected call of ListScheduledJobs.
func (mr *MockRepositoryMockRecorder) ListScheduledJobs(ctx, scheduledJobID, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduledJobs", reflect.TypeOf((*MockRepository)(nil).ListScheduledJobs), ctx, scheduledJobID, userID, cursor)
}

// ScheduleJob mocks base method.
func (m *MockRepository) ScheduleJob(ctx context.Context, jobID, userID, scheduledAt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleJob", ctx, jobID, userID, scheduledAt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleJob indicates an expected call of ScheduleJob.
func (mr *MockRepositoryMockRecorder) ScheduleJob(ctx, jobID, userID, scheduledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleJob", reflect.TypeOf((*MockRepository)(nil).ScheduleJob), ctx, jobID, userID, scheduledAt)
}

// TerminateJob mocks base method.
func (m *MockRepository) TerminateJob(ctx context.Context, jobID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateJob", ctx, jobID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateJob indicates an expected call of TerminateJob.
func (mr *MockRepositoryMockRecorder) TerminateJob(ctx, jobID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateJob", reflect.TypeOf((*MockRepository)(nil).TerminateJob), ctx, jobID, userID)
}

// UpdateJob mocks base method.
func (m *MockRepository) UpdateJob(ctx context.Context, jobID, userID, name, payload string, interval int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", ctx, jobID, userID, name, payload, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockRepositoryMockRecorder) UpdateJob(ctx, jobID, userID, name, payload, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockRepository)(nil).UpdateJob), ctx, jobID, userID, name, payload, interval)
}

// UpdateJobBuildStatus mocks base method.
func (m *MockRepository) UpdateJobBuildStatus(ctx context.Context, jobID, buildStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobBuildStatus", ctx, jobID, buildStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobBuildStatus indicates an expected call of UpdateJobBuildStatus.
func (mr *MockRepositoryMockRecorder) UpdateJobBuildStatus(ctx, jobID, buildStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobBuildStatus", reflect.TypeOf((*MockRepository)(nil).UpdateJobBuildStatus), ctx, jobID, buildStatus)
}

// UpdateScheduledJobStatus mocks base method.
func (m *MockRepository) UpdateScheduledJobStatus(ctx context.Context, scheduledJobID, scheduledJobStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduledJobStatus", ctx, scheduledJobID, scheduledJobStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduledJobStatus indicates an expected call of UpdateScheduledJobStatus.
func (mr *MockRepositoryMockRecorder) UpdateScheduledJobStatus(ctx, scheduledJobID, scheduledJobStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduledJobStatus", reflect.TypeOf((*MockRepository)(nil).UpdateScheduledJobStatus), ctx, scheduledJobID, scheduledJobStatus)
}
