// Code generated by MockGen. DO NOT EDIT.
// Source: jobs.go
//
// Generated by this command:
//
//	mockgen -source=jobs.go -package=jobs -destination=./mock/jobs.go
//

// Package jobs is a generated GoMock package.
package jobs

import (
	context "context"
	reflect "reflect"

	model "github.com/hitesh22rana/chronoverse/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockRepository) CreateJob(ctx context.Context, userID, name, payload, kind string, interval, maxRetry int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, userID, name, payload, kind, interval, maxRetry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockRepositoryMockRecorder) CreateJob(ctx, userID, name, payload, kind, interval, maxRetry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockRepository)(nil).CreateJob), ctx, userID, name, payload, kind, interval, maxRetry)
}

// GetJob mocks base method.
func (m *MockRepository) GetJob(ctx context.Context, jobID, userID string) (*model.GetJobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID, userID)
	ret0, _ := ret[0].(*model.GetJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockRepositoryMockRecorder) GetJob(ctx, jobID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockRepository)(nil).GetJob), ctx, jobID, userID)
}

// GetJobByID mocks base method.
func (m *MockRepository) GetJobByID(ctx context.Context, jobID string) (*model.GetJobByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByID", ctx, jobID)
	ret0, _ := ret[0].(*model.GetJobByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByID indicates an expected call of GetJobByID.
func (mr *MockRepositoryMockRecorder) GetJobByID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByID", reflect.TypeOf((*MockRepository)(nil).GetJobByID), ctx, jobID)
}

// ListJobsByUserID mocks base method.
func (m *MockRepository) ListJobsByUserID(ctx context.Context, userID, cursor string) (*model.ListJobsByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobsByUserID", ctx, userID, cursor)
	ret0, _ := ret[0].(*model.ListJobsByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobsByUserID indicates an expected call of ListJobsByUserID.
func (mr *MockRepositoryMockRecorder) ListJobsByUserID(ctx, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobsByUserID", reflect.TypeOf((*MockRepository)(nil).ListJobsByUserID), ctx, userID, cursor)
}

// ListScheduledJobs mocks base method.
func (m *MockRepository) ListScheduledJobs(ctx context.Context, jobID, userID, cursor string) (*model.ListScheduledJobsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduledJobs", ctx, jobID, userID, cursor)
	ret0, _ := ret[0].(*model.ListScheduledJobsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduledJobs indicates an expected call of ListScheduledJobs.
func (mr *MockRepositoryMockRecorder) ListScheduledJobs(ctx, jobID, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduledJobs", reflect.TypeOf((*MockRepository)(nil).ListScheduledJobs), ctx, jobID, userID, cursor)
}

// UpdateJob mocks base method.
func (m *MockRepository) UpdateJob(ctx context.Context, jobID, userID, name, payload, kind string, interval int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", ctx, jobID, userID, name, payload, kind, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockRepositoryMockRecorder) UpdateJob(ctx, jobID, userID, name, payload, kind, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockRepository)(nil).UpdateJob), ctx, jobID, userID, name, payload, kind, interval)
}
